apiVersion: v1
kind:       Service
metadata:
  name: k8-start-service
  labels:
    app: k8-start-service
spec:
  ports:
    - port:       8080
      targetPort: 8080
      nodePort:   30030
  selector:
    app: k8-start-service
  type: NodePort
