apiVersion: v1
kind:       Service
metadata:
  name: k8-intra-pod-communication-service
  labels:
    app: k8-intra-pod-communication-service
spec:
  ports:
    - name: start-service
      port:       8080
      targetPort: 8080
      nodePort:   30030
    - name: end-service
      port:       9090
      targetPort: 9090
      nodePort:   30040
  selector:
    app: k8-intra-pod-communication-deploy
  type: NodePort
