apiVersion: v1
kind:       Service
metadata:
  name: k8-end-service
  labels:
    app: k8-end-service
spec:
  ports:
    - port:       9090
      targetPort: 9090
      nodePort:   30040
  selector:
    app: k8-end-service
  type: NodePort
